import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`p-4`}>
        <div className="mb-8">
          <Link href="/"><h1 className='text-8xl text-red-600'>NEXTflix</h1></Link>
          <h1 className='text-2xl text-gray-300'>All the heat. Get ready for <span className='font-bold'>Next</span>-level entertainment.</h1>
        </div>
        {children}
      </body>
    </html>
  )
}
